# Generated by Django 3.0.5 on 2020-05-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='timestamp',
        ),
    ]
